fix: update client types path in core package.json (#326)
```bash
> tsc && vite build

error TS2688: Cannot find type definition file for 'vite/client'.
  The file is in the program because:
    Entry point of type library 'vite/client' specified in compilerOptions

  tsconfig.json:7:15
    7     "types": ["vite/client"],
                    ~~~~~~~~~~~~~
    File is entry point of type library specified here.


Found 1 error.
```